travis:
  secure:
    BINSTAR_TOKEN: TlkPv+8Q2VAHzuxqhFR/mWou82fhDqTOouwFQp38VXK+2f73OwGravLv5HZJQ2XSrrJyCd+ELh2Hgd6t98q5Qpr/lvqaTKgGnnLQljO5OOpIF2z2ZvyiII6aczpDX5EGQko0in5mTi0K7pxqnvcCMpGkxbZRix4BHul+Q4z8Czql43nRKAifYfKpzbeT9PowJ+/ugd9DgYBj9MbDJr8Kgx2ome/69FDxXawUdK0EWLDNj39lVMy2e+YiP/MTQZBjfNHDgdh3GTSNulTSYqzlRMr63rYlRIoxKah8Fw51JKY+eWJx2K6jHCxpyl7icfIZzam1i+4zcEexA2pL3NkA3VOpRlLURVZNliIIHZ1mAYTzs0cIOoLLkCh0CYwnyNAarCc477NsCfELgog7z2E0POBf7Q49hYaqKn/wfgRRHetnNP7vdaf5Ns0KYB57Hm64KvDgkdADKQS4Y4iqG/I0MFDqIdUWBtNwjJpqX9X26b4oF8Rioul3ERsIWJ5Oc/0Xz8o5PzZhyF+FZQSMrySJzXR4R7MJGALZW3vHDWdSRJ5s1ATk+ec4WYweViALqngtlqfmakpvv6UO/4/i00v+L/2svwphLLQuQ06AqxCHbbSAnpGM/t7ZKrJa8x793SDPb8BRCFifhCLV5QWTkwxDImcMMznwsoMvvIgGWgW1eNQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
